[header]
version = "1.0"

[define]
validModes = ["insert", "capture", "normal"]

[[bind]]
name = "normal mode"
key = "escape"
command = "runCommands"
args = ["master-key.enterNormal", "master-key.reset"]
prefixes = "<all-prefixes>"

[[path]]
id = "motion"
name = "basic motions"
default.command = "cursorMove"
default.mode = "normal"
default.when = "editorTextFocus"

[[bind]]
path = "motion"
name = "left"
key = "h"
args.to = "left"

[[bind]]
path = "motion"
name = "right"
key = "l"
args.to = "right"

[[bind]]
path = "motion"
name = "down"
key = "j"
args.to = "down"

[[bind]]
path = "motion"
name = "up"
key = "k"
args.to = "up"
