[header]
version = "1.0"

[define]
validModes = ["insert", "capture", "left"]

[[bind]]
name = "left mode"
key = "ctrl+shift+r"
command = "master-key.setMode"
args.value = "right"

[[bind]]
name = "move right"
key = "ctrl+g ctrl+f"
command = "moveCursor"
args.to = "right"
when = "editorTextFocus"

[[bind]]
name = "move left"
mode = "left"
key = "ctrl+g ctrl+f"
command = "moveCursor"
args.to = "left"
when = "editorTextFocus"

[[bind]]
name = "prepare select"
key = "ctrl+l"
command = "master-key.prefix"
args.flag = "select"
resetTransient = false

[[path]]
id = "word"
name = "word"
default.prefixes = ["", "ctrl+l"]

[[bind]]
path = "word"
name = "word motion"
key = "ctrl+shift+w"
when = "!master-key.select"
command = "cursorWordRight"

[[bind]]
path = "word"
name = "word motion"
key = "ctrl+shift+w"
when = "!master-key.select"
mode = "left"
command = "cursorWordLeft"

[[bind]]
path = "word"
key = "ctrl+shift+w"
when = "master-key.select"
command = "cursorWordRightSelect"

[[bind]]
path = "word"
key = "ctrl+shift+w"
mode = "left"
when = "master-key.select"
command = "cursorWordLeftSelect"

[[bind]]
name = "set foo"
key = "ctrl+alt+w"
command = "master-key.set"
args.name = "foo"
args.value = 2

[[bind]]
name = "write foo"
key = "ctrl+alt+l"
command = "type"
computedArgs.text = "foo"
