name: Integration Tests
on:
    push:
        branches:
            - main
        tags:
            - v[0-9]+.[0-9]+.[0-9]+*
    pull_request:
        types: ['opened', 'edited', 'reopened', 'synchronize', 'ready_for_review']
jobs:
    test:
        if: '! github.event.pull_request.draft'
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Cache Node and Playwright Builds
          uses: actions/cache@v4
          with:
            key: mise-unit-${{ hashFiles(format('{0}/mise.toml {0}/pnpm-lock.yaml', github.workspace)) }}
            path: >-
                ${{ github.workspace }}.vscode-test/**/*
                ${{ github.workspace }}.vscode-test-web/**/*
                ${{ github.workspace }}/node_modules/**/*
        - name: Install Dev Environment
          uses: jdx/mise-action@v2
          with:
            version: 2025.6.4
            install: true
            cache: true
            experimental: true
        - name: Run Playwright tests
          uses: coactions/setup-xvfb@v1
          with:
            run: mise run test-integration
        - uses: actions/upload-artifact@v4
          if: ${{ !cancelled() }}
          with:
              name: playwright-report
              path: playwright-report/
              retention-days: 30
