name: Unit Tests
on:
    push:
        branches:
            - main
        tags:
            - v[0-9]+.[0-9]+.[0-9]+*
    pull_request:
        types: ['opened', 'edited', 'reopened', 'synchronize', 'ready_for_review']

jobs:
    test:
        if: '! github.event.pull_request.draft'
        strategy:
            matrix: { environment: [web, desktop] }
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Debug Directory Info
          run: ls -la ${{github.workspace}} && ls -la ${{github.workspace}}/vscode-master-key
        - name: Install pnpm
          uses: pnpm/action-setup@v4
          with:
            version: 10
        - name: Cache/setup pnpm ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'pnpm'
        - name: Cache Browser Builds
          uses: actions/cache@v4
          with:
            key: mise-unit-${{ hashFiles('{0}/vscode-master-key/mise.toml {0}/vscode-master-key/pnpm-lock.yaml', github.workspace) }}
            path: >-
                ${{ github.workspace }}/vscode-master-key/.vscode-test
                ${{ github.workspace }}/vscode-master-key/.vscode-test-web
                ~/.cache
        - name: Install Dev Environment
          uses: jdx/mise-action@v2
          with:
            version: 2025.6.4
            install: true
            cache: true
            experimental: true
        - name: Run Desktop Unit Tests
          if: matrix.environment == 'desktop'
          uses: coactions/setup-xvfb@v1
          with:
            run: mise test
        - name: Run Web Unit Tests
          if: matrix.environment == 'web'
          uses: coactions/setup-xvfb@v1
          with:
            run: mise test-web
        - name: Verify working directory info
          run: echo "${{github.workspace}}"
