name: Unit Tests
on:
    push:
        branches:
            - main
        tags:
            - v[0-9]+.[0-9]+.[0-9]+*
    pull_request:
        types: ['opened', 'edited', 'reopened', 'synchronize', 'ready_for_review']

jobs:
    test:
        if: '! github.event.pull_request.draft'
        strategy:
            matrix: { environment: [web, desktop] }
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Cache Build
              uses: actions/cache@v4
              with:
                path: ~/.cache/** node_modules/**
                key: mise-unit-${{ hashFiles('mise.toml pnpm-lock.yaml') }}
            - name: Install Dev Environment
              uses: jdx/mise-action@v2
              with:
                version: 2025.6.4
                install: true
                cache: true
            - name: Run Desktop Unit Tests
              if: matrix.environment == 'desktop'
              uses: coactions/setup-xvfb@v1
              with:
                run: mise test
            - name: Run Web Unit Tests
              if: matrix.environment == 'web'
              uses: coactions/setup-xvfb@v1
              with:
                run: mise test-web
